- hosts: regru-test
  vars:
    sudoers:
      - chimera

  tasks:
    - name: Add the user 'chimera' if not exist
      user:
        name: chimera
        state: present

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: "{{ sudoers }}"

    - name: Restart service sshd, in all cases
      service:
        name: sshd
        state: restarted

    - name: Install fail2ban
      apt:
        name:
          - fail2ban
        state: present
        update_cache: yes


    - name: Copy jail.conf to server
      copy:
        src: files/jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        backup: yes

    - name: Update packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install ufw
      apt:
        name:
          - ufw
        state: present
        update_cache: yes

    - name: Allow ssh
      community.general.ufw:
        rule: allow
        port: ssh

    - name: Allow http
      community.general.ufw:
        rule: allow
        port: http

    - name: Allow https
      community.general.ufw:
        rule: allow
        port: https

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Install build-essential & prepare for installing glances
      apt:
        name:
          - build-essential
          - python3
          - python3-dev
          - python3-jinja2
          - python3-psutil
          - python3-setuptools
          - hddtemp
          - python3-pip
          - lm-sensors
        state: present
        update_cache: yes

    - name: Install glances
      pip:
        name: pip
        extra_args: install glances
        executable: pip3
