- hosts: "{{ variable_host }}"
  vars:
    admin_user: "{{ admin_user }}"
    sudoers:
      - "{{ admin_user }}"

  tasks:
    - name: Setting up admin user (1/4)
      user:
        name: "{{ admin_user }}"
        state: present

    - name: Setting up admin user (2/4)
      group:
        name: wheel
        state: present

    - name: Setting up admin user (3/4)
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Setting up admin user (4/4)
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: "{{ sudoers }}"

    - name: Setting up ssh daemon properly (1/2)
      copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        backup: yes

    - name: Setting up ssh daemon properly (2/2)
      service:
        name: sshd
        state: restarted

    - name: Setting up fail2ban (1/2)
      apt:
        name:
          - fail2ban
        state: present
        update_cache: yes

    - name: Setting up fail2ban (2/2)
      copy:
        src: files/jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        backup: yes

    - name: Update packages
      apt: upgrade=dist force_apt_get=yes

    - name: Setting up ufw (1/5)
      apt:
        name:
          - ufw
        state: present
        update_cache: yes

    - name: Setting up ufw (2/5)
      community.general.ufw:
        rule: allow
        port: ssh

    - name: Setting up ufw (3/5)
      community.general.ufw:
        rule: allow
        port: http

    - name: Setting up ufw (4/5)
      community.general.ufw:
        rule: allow
        port: https

    - name: Setting up ufw (5/5)
      community.general.ufw:
        state: enabled

    - name: Installing useful packages (build-essential & glances for monitoring) (1/2)
      apt:
        name:
          - build-essential
          - python3
          - python3-dev
          - python3-jinja2
          - python3-psutil
          - python3-setuptools
          - hddtemp
          - python3-pip
          - lm-sensors
        state: present
        update_cache: yes

    - name: Installing useful packages (build-essential & glances for monitoring) (2/2)
      pip:
        name: pip
        extra_args: install glances
        executable: pip3
